[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/feedback"
  to = "/feedback.html"
  status = 200

[build]
  publish = "."

[functions]
  directory = "netlify/functions"
